language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
script:
  - nosetests -v geobricks_trmm_test/core/test_trmm_core.py
  - nosetests -v geobricks_trmm_test/rest/test_trmm_rest.py